from .ozon import get_price_and_name_frm_ozon
from .sber_market import get_price_and_name_frm_smm
from .wildberries import get_price_and_name_frm_wildberries
from .yandex_market import get_price_and_name_frm_ymarket
from .aliexpress import get_price_and_name_frm_aliexpress
